Oh good you found my computer! You might ask why someone would bury a computer in their back yard. That is a valid question but to get to the bottom of that mistery it requires some work on you part....


